# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Card Grid - Four Column
  description: Card grid with four locations
  icon: 'view_comfy'
  tags: ['Grid']

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  description:
  cards:
    - title:
      img:
      path:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: textarea
