# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left Right - Quote
  description: Left Right with quote.
  icon: 'view_sidebar'
  tags: ['Left Right']

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#090303'
  text_color: '#FFFFFF'
  location:
    city: Austin
    state: Texas
  image:
    src: /images/work/austin-before-after.webp
  title: Transform Your Online Dating Profile
  quote:
    background_color: '#FFFFFF'
    text_color: '#090303'
    text: Before getting pics taken by The Match Artist, I was getting 2-3
      tinder matches a week. After getting new high value pictures from
      The Match Artist and tweaking my bio I was getting over 5 matches
      per day with really great girls. The results truly speak for
      themselves.
    person: Cameron T
  cta:
    title: Stand Out in the Digital Dating Scene
    button:
      text: Enquire Now
      background_color: '#990800'
    stats:
      - number: 1000
        text: Successful Clients
      - number: 20
        text: Marriages
      - number: 250
        text: Relationships
  button:
    path: '#contact'
    text: Book a Call

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
