# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Hero section for the top of a page.
  icon: 'cottage'
  tags: ['Hero']

# Defines the structure of this component, as well as the default values
blueprint:
  background_color:
  background_image:
  background_filters:
    brightness: 1
    blur: 0
  pre_title:
    text:
    text_color:
    top_spacing:
    bottom_spacing:
  title:
    text:
    text_color:
    heading_style: h1
    top_spacing:
    bottom_spacing:
  post_title:
    text:
    text_color:
    top_spacing:
    bottom_spacing:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea
  heading_style:
    type: select
    comment: Used to control the headings sematic value, leave this as h1 if this is the pages main heading.
    options:
      values:
        - h1
        - h2
  background_color:
    type: color
    comment: This is used to set the background color if no background image is present.
  background_filters:
    comment: Change the brightness and blur of the background image.
    hidden: '!background_image'
