# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left Right - Phone
  description: Left Right with phone mockup.
  icon: 'view_sidebar'
  tags: ['Left Right']

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#E5E5E5'
  text_color: '#090303'
  image:
    src: /images/mockups/tindermock.webp
    height: 812
    width: 375
  title: Elevate Your Dating Profile with Professional Dating Photography
  description: In a picture-first dating world, make sure your profile photo
    entices prospects to explore further and discover your true
    potential.
  list:
    - icon: /icons/camera.svg
      text: Make a great first impression
    - icon: /icons/heart.svg
      text: Get more matches
    - icon: /icons/magnifying-glass.svg
      text: Go on better dates
    - icon: /icons/gold-star.svg
      text: Feel more confident
  button:
    path: '#contact'
    text: Book a Call

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
