# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Image slider
  description: Image slider section with supporting text and bg image.
  icon: 'linear_scale'
  tags: ['Slider']

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#090303'
  text_color: '#FFFFFF'
  location:
    city: Austin
    state: Texas
  title: Full Photoshoot In Different Settings To Capture The Best You
  description: Our approach involves capturing a multitude of photos to ensure we curate a selection that shows your personality, helping you stand out on dating platforms.
  background_image: /images/backgrounds/city-background-detailed.jpeg
  images:
    - /images/work/brent.webp
    - /images/team/brian.webp
  testimonial:
    text:
      Before getting pics taken by The Match Artist, I was getting 2-3 tinder
      matches a week. After getting new high value pictures from The Match
      Artist and tweaking my bio I was getting over 5 matches per day with
      really great girls. The results truly speak for themselves.
    person: Cameron T.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
