# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Card Grid
  description: Card grid with two columns
  icon: 'apps'
  tags: ['Grid']

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  cards:
    - title:
      subtitle:
      description:
      image:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  bio:
    type: markdown
