# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Page Banner - Stats
  description: Full width page banner for displaying stats
  icon: 'panorama_horizontal'
  tags: ['Banner']

# Defines the structure of this component, as well as the default values
blueprint:
  background_color:
  background_image:
  background_filters:
    brightness: 1
    blur: 0
  top_spacing:
  bottom_spacing:
  text_color:
  title:
    text:
    top_spacing:
    bottom_spacing:
    text_color:
  stats:
    - stat:
      text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_filters:
    hidden: '!background_image'
    comment: Change the brightness and blur of the background image.
