# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero - Left Right - Location
  description: Hero section for the top of the page in a left right format with variable location
  icon: 'cottage'
  tags: ['Hero']

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#00000'
  text_color: '#FFFFFF'
  location:
    city: Austin
    state: Texas
  image:
    src: /images/team/brian.webp
    alt: Photo of Brian on a black background
    max_width: 500
  testimonial:
    text: 'An overall skyrocketing experience for my online dating.'
    person: Brent S
    image:
      src: /images/work/brent.webp
      alt: Photo of Brent
      height: 50
      width: 50
    height: 54
    width: 365
    vertical_padding: 40
    horizontal_padding: 9
  button:
    path: '#contact'
    text: Book a Call

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  latitude:
    type: number
  longitude:
    type: number
  city:
    type: select
    options:
      values: data.locations
      value_key: city
      preview:
        text:
          - key: city
  state:
    type: select
    options:
      values: data.locations
      value_key: state
      preview:
        text:
          - key: state
