# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Quote
  description: A quote block
  icon: 'format_quote'
  tags: ['Quote']

# Defines the structure of this component, as well as the default values
blueprint:
  quote:
  author:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  quote:
    type: textarea
